server:
  port: 8500
spring:
  application:
    name: spzx-server-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            # 允许请求中携带的头信息,表示允许所有来源的跨域请求。
            allowedHeaders: "*"
            # 运行跨域的请求方式
            allowedMethods: "*"
            # 跨域检测的有效期,单位s
            maxAge: 36000
      routes:
        - id: service-product
          #该路由规则对应的微服务实例，使用负载均衡的方式进行转发。
          uri: lb://service-product
          predicates:
            - Path=/*/product/**
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**
        - id: service-cart
          uri: lb://service-cart
          predicates:
            - Path=/api/order/cart/**
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/api/order/orderInfo/**
        - id: service-pay
          uri: lb://service-pay
          predicates:
            - Path=/api/order/alipay/**
  # Redis的相关配置
  data:
    redis:
      host: 192.168.10.100
      port: 6379